export const DELETE_LIKE_TEAMS_SUCCESS = "DELETE_LIKE_TEAMS_SUCCESS";
export const DELETE_LIKE_PLAYERS_SUCCESS = "DELETE_LIKE_PLAYERS_SUCCESS";

export const SAVE_LIKE_TEAMS_SUCCESS = "SAVE_LIKE_TEAMS_SUCCESS";
export const SAVE_LIKE_PLAYERS_SUCCESS = "SAVE_LIKE_PLAYERS_SUCCESS";


export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_FAILED = "FETCH_TEAMS_FAILED";



export const FETCH_PLAYERS_SUCCESS = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_REQUEST = "FETCH_PLAYERS_REQUEST";
export const FETCH_PLAYERS_FAILED = "FETCH_PLAYERS_FAILED";