export const DELETE_LIKE_TEAMS_SUCCESS = "DELETE_LIKE_TEAMS_SUCCESS";
export const DELETE_LIKE_PLAYERS_SUCCESS = "DELETE_LIKE_PLAYERS_SUCCESS";

export const SAVE_LIKE_TEAMS_SUCCESS = "SAVE_LIKE_TEAMS_SUCCESS";
export const SAVE_LIKE_PLAYERS_SUCCESS = "SAVE_LIKE_PLAYERS_SUCCESS";